FROM python:3.10-slim
WORKDIR /app

COPY requirements.txt .
RUN pip install --no-cache-dir streamlit plotly pandas requests numpy

COPY dashboard/ ./dashboard/
COPY reports/ ./reports/
COPY models/ ./models/
COPY src/ ./src/

EXPOSE 8501

CMD ["streamlit", "run", "dashboard/app.py", "--server.port", "8501", "--server.address", "0.0.0.0"]
